### ISSUE TITLE
Installing package with apt-get into micromamba container in Gitlab pipeline

### ISSUE THREAD

**Issue by danieljuschus** [mamba-org/micromamba-docker#252]
I need a package in my pipeline, which using miniconda I can install directly in my `.gitlab-ci.yml file`:

```yaml
image: continuumio/miniconda3:latest

before_script:
  - apt-get update && apt-get install -y libgl1-mesa-glx
  - conda env create -f environment.yml
 etc.
```

When I change this to `image:mambaorg/micromamba:1.1.0-bullseye`, it fails:

```
Reading package lists...
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
```

On [Stackoverflow](https://stackoverflow.com/questions/74934447/how-to-install-package-with-apt-get-in-gitlab-ci-pipeline-using-micromamba-image) I was already told that with the miniconda image, the user is root by default, whereas with micromamba it isn't. I'm therefore wondering, what would be the best way to achieve this?

Is there a way to change the user to root within my pipeline yml file? Wouldn't this be a safety risk?

I also tried cloning the repo, in order to modify the Dockerfile with `apt-get install -y libgl1-mesa-glx`. However, before even doing so, the local build fails, as I explained in https://github.com/mamba-org/micromamba-docker/issues/251.

I'm a beginner with docker, so sorry if this isn't actually a bug, but perhaps it would be good to add a sentence or two to the readme for people like me.
