### ISSUE TITLE
The following argument was not expected: --prefix

### ISSUE THREAD

**Issue by mpizenberg** [mamba-org/micromamba-docker#287]
Hi, I’ve configured a docker container based on the micromamba-docker image as follows.

```dockerfile
FROM mambaorg/micromamba:alpine AS builder

# ... some stuff

# Install a bare conda environment with just python
USER $MAMBA_USER
RUN micromamba create -n ids -c conda-forge --yes python=3.10

# Lightweight(ish) runner container
FROM mambaorg/micromamba:alpine AS runner
# Switch to root to install system dependencies
USER root
RUN apk add --no-cache libstdc++ # required by pyright
COPY --from=builder $MAMBA_ROOT_PREFIX $MAMBA_ROOT_PREFIX
USER $MAMBA_USER
WORKDIR /home/$MAMBA_USER
```

It’s working as expected when I’m testing the docker container on my machine. However, when I’m in the GitLab CI there is something wrong. Here is the relevant part of my gitlab-ci.yml file.

```yml
# Check static code analysis
static-analysis:
  image: ......./ids-peak-python
  script:
    # Copy pre-filled environment into venv
    - mkdir -p venv/ids_peak
    - cp -r /opt/conda/envs/ids/* venv/ids_peak/
    # Activate the newly copied environment
    - micromamba activate --prefix venv/ids_peak      # <- it crashes here
    # Install the rest of the CI conda dependencies
    - micromamba install -f environment-ci.yml --yes
    # Install the python packages CI deps
    - pip-sync requirements/ci.txt
    # Check static code analysis
    - pyright --version
    - pyright examples/
```

When I’m doing the same locally in the container, everything works. But in GitLab ci, I’m getting the following error message.

```
$ mkdir -p venv/ids_peak
$ cp -r /opt/conda/envs/ids/* venv/ids_peak/
$ micromamba activate --prefix venv/ids_peak
The following argument was not expected: --prefix
Run with --help for more information.
Cleaning up project directory and file based variables 00:00
ERROR: Job failed: exit code 1
```

The version of micromamba in the container is 1.4.1.

Any idea on what is going on?

**Comment by wholtz** [comment]
Hi @mpizenberg - thanks for the report and your interest in micromamba.

`micromamba activate ...` is a bash function call, not a direct execution of the `micromamba` binary. I'm guessing that the bash function is not getting loaded in the environment that GitLab CI provides (most likely because it overrides our entrypoint script).  As a work around, you could do this:

```yaml
# Check static code analysis
static-analysis:
  image: ......./ids-peak-python
  script:
    # Copy pre-filled environment into venv
    - mkdir -p venv/ids_peak
    - cp -r /opt/conda/envs/ids/* venv/ids_peak/
    # Install the rest of the CI conda dependencies
    - micromamba install --prefix venv/ids_peak  -f environment-ci.yml --yes
    # Install the python packages CI deps
    - micromamba run --prefix venv/ids_peak pip-sync requirements/ci.txt
    # Check static code analysis
    - micromamba run --prefix venv/ids_peak pyright --version
    - micromamba run --prefix venv/ids_peak pyright examples/
```
