### ISSUE TITLE
Switch from miniconda for Gitlab CI?

### ISSUE THREAD

**Issue by JackLidge** [mamba-org/micromamba-docker#353]
Apologies if this is the wrong place to put this - I have a project with GitLab CI pipelines which was previously set up to use a miniconda docker image and I would like to switch it to use this docker image. However, I'm not sure how to get mamba activated within the GitLab action. I've had a look at previous issues here and also Googled but haven't found anything for this specific use case.

This is my current .gitlab-ci.yml file:
```
image: continuumio/miniconda3:latest

testbuild:
    stage: build
    script: 
        - conda env create -f environment.yml
        - conda activate piml
        - conda install -c conda-forge pytest
        - pip install piproc amqpstorm
        - cd tests && pytest
```

I tried swapping out the image and then replacing "conda" with "mamba" for the env create and pytest install steps which gave the following error:
`/bin/bash: line 131: mamba: command not found`.

Then I tried just swapping out the image but leaving the rest intact, which gave the following error:
`/bin/bash: line 131: conda: command not found` which I suppose was to be expected.

Any help with this much appreciated, I'm sure there's something simple I'm missing.
