### ISSUE TITLE
Unexpected behaviour with cuda. 

### ISSUE THREAD

**Issue by DemirTonchev** [mamba-org/micromamba-docker#388]
When building a nvidia drivers image with micromamba as explained in https://micromamba-docker.readthedocs.io/en/latest/advanced_usage.html#adding-micromamba-to-an-existing-docker-image 

with this env file 
```yml
name: base
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pytorch
  - numpy
  - pytorch-cuda=12.1
  - python=3.10
```
all works as expected and pytorch is installed with cuda. But if 
```yml
channels:
  - conda-forge
  - pytorch
  - nvidia
```
is used (conda-forge is first), then the cpu only version of pytorch is installed. Is this a bug or expected behaviour?

My expectation is that channel order does not matter. 

Thanks
