### ISSUE TITLE
Question: can we pass extra-url to the env.yaml?

### ISSUE THREAD

**Issue by LumenYoung** [mamba-org/micromamba-docker#452]
Hi, thanks for this great development environment. 

I would like to ask a question regarding the pip install supported in the env.yaml, this a thing because the pip and conda way of installing pytorch sometimes lead to undesired cpu version. So I use the following way to enforce a pytorch vision suitable for my need as following: `pip install torch==2.1.2+cu121 torchvision==0.17.1+cu121 --extra-index-url https://download.pytorch.org/whl/cu121`

In the normal micromamba, I can just use command line interface, but since micromamba way of installing only support env.yaml. I would like to ask whether I have a way to pass that to a pip field?

Something like:

```yaml
name: robodiff
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pip=22.2.2
  - pip:
    - torch==2.1.2+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
```

I've looked at the docs and find no mention of this question, please correct me if I'm wrong. Thanks for all the help in advance!
