### ISSUE TITLE
Env not activated when conda-build package installed

### ISSUE THREAD

**Issue by mattijsdp** [mamba-org/micromamba-docker#574]
Hi, I have the following very easy reproducible example that doesn't work as expected (I think).

I have two `conda.yaml` files:

`conda.yaml`
```yaml
name: base
channels:
  - conda-forge
dependencies:
  - python=3.11
 ```

`conda.yaml` - same yaml but also installing `conda-build`
```yaml
name: base
channels:
  - conda-forge
dependencies:
  - python=3.11
  - conda-build
 ```

I then create an image with the following Dockerfile (all in the same directory):
```
FROM mambaorg/micromamba:jammy

COPY conda.yaml .
RUN micromamba install -y -n base -f conda.yaml && \
    micromamba clean --all --yes
```

`docker build . -t micromamba-test`

When I run the first one (without conda-build), I get the expected result:
```shell
docker run -it micromamba-test python --version
Python 3.11.11
```

When I run the second one (with conda-build), it simply exits and no version is printed:
 ```shell
docker run -it micromamba-test python --version
```

I am guessing because conda-build allows you to install packages in development mode it somehow interferes with activating the env?
